### ISSUE TITLE
caffe2 dependency

### ISSUE THREAD

**Issue by saeede-askari** [zcxu-eric/AVA-AVD#6]
@zcxu-eric Could you please take a look at this issue? I'm experiencing a problem with this error:

Traceback (most recent call last):
  File "model/mmsc_exp/run.py", line 125, in <module>
    run()
  File "model/mmsc_exp/run.py", line 81, in run
    setup_imports()
  File ".../AVA-AVD/model/mmsc/utils/env.py", line 187, in setup_imports
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../AVA-AVD/model/mmsc/trainers/mmsc_trainer.py", line 17, in <module>
    from mmsc.trainers.core.evaluation_loop import TrainerEvaluationLoopMixin
  File ".../AVA-AVD/model/mmsc/trainers/core/evaluation_loop.py", line 9, in <module>
    from caffe2.python.timeout_guard import CompleteInTimeOrDie
ModuleNotFoundError: No module named 'caffe2'

Since the 'caffe2' module is not mentioned in the requirements file, I guess the codebase should be updated to use PyTorch instead of Caffe2. So I don't know if the error message is real or outdated. I was wondering if you have any comment on this error.

**Comment by zcxu-eric** [comment]
Hi, this is a bug from the codebase. Plz disable the complete time check in ".../AVA-AVD/model/mmsc/trainers/core/evaluation_loop.py" line 9.

**Comment by picheny-nyu** [comment]
@zcxu-eric  I commented out the above import statement but then it does not find "CompleteInTimeOrDie" on line 44 in the above code. How can I fix this?

Thanks
Michael Picheny
